---
- name: Create dockhand folder
  ansible.builtin.file:
    path: "{{ deploy_path }}/dockhand"
    state: directory
    mode: '0755'

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml
    dest: "{{ deploy_path }}/dockhand/compose.yml"
    mode: '0644'

- name: Start dockhand
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/dockhand"
  become: true
  register: dockhand_output
