---

- name: Create paperless folder
  ansible.builtin.file:
    path: "{{ deploy_path }}/paperless"
    state: directory
    mode: '0755'

- name: Copy env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ deploy_path }}/paperless/.env"
    mode: '0644'

- name: Copy compose file
  ansible.builtin.template:
    src: compose.yml
    dest: "{{ deploy_path }}/paperless/compose.yml"
    mode: '0644'

- name: Start paperless
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/paperless"
  become: true
