---

- name: Disable systemd resolved stub listener
  ansible.builtin.import_role:
    name: utils
    tasks_from: disable-systemdresolved-stub.yml

- name: Create technitium folder
  ansible.builtin.file:
    path: "{{ deploy_path }}/technitium"
    state: directory
    mode: '0755'

- name: Copy technitium compose file
  ansible.builtin.template:
    src: compose.yml
    dest: "{{ deploy_path }}/technitium/compose.yml"
    mode: '0644'

- name: Start technitium
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_path }}/technitium"
  become: true
  register: technitium_output
