services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    networks:
      proxy:
    ports:
      - "127.0.0.1:5380:5380/tcp" #DNS web console (HTTP)
      - "53443:53443/tcp" #DNS web console (HTTPS), exposed for clustering
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
    environment:
      #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_DOMAIN={{ dns_url }}
      - DNS_SERVER_ADMIN_PASSWORD={{ dns.technitium.password }}
    volumes:
      - ./config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.technitium.loadbalancer.server.port=5380"
      - "traefik.http.routers.technitium.rule=Host(`{{ dns_url }}`)"
    healthcheck:
      test: ["CMD-SHELL", "dig +short +retry=0 +norecurse @127.0.0.1 SOA localhost || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  proxy:
    external: true
